spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/invoice_db
    username: admin
    password: 930610
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
